### ISSUE TITLE
Lab doesn't work with Benthos v3.2.1 (seems like it's Go 1.13)

### ISSUE THREAD

**Issue by ilyaglow** [benthosdev/benthos-lab#18]
I tried to build a lab with the latest benthos version (3.2.1) that [requires Go 1.13](https://github.com/Jeffail/benthos/blob/master/go.mod#L100).

It builds successfully with a few Dockerfile changes, but the `Attempting to initialise Benthos engine...` message doesn't disappear when I visit UI.

In the browser's console I see the following error:
```
(index):1 Uncaught (in promise) LinkError: WebAssembly.instantiate(): Import #20 module="go" function="syscall/js.copyBytesToGo" error: function import requires a callable
Promise.then (async)
(anonymous) @ editor.js:400
```

I noticed that whatever version of benthos I try to build with Go 1.13 in the lab I get the same error.

**Comment by Jeffail** [comment]
Looks like it's this: https://github.com/golang/go/issues/29827#issuecomment-455747409

Just need to remember that any time we upgrade the version of Go we also need to update the `.js` file that comes with it. I'll update later today and add comments on our docker images as a reminder for next time.

**Comment by Jeffail** [comment]
Looks like there's also a regression so we might not be able to upgrade to 1.13 until this is resolved https://github.com/golang/go/issues/34395

**Comment by DpoBoceka** [comment]
Looks like it's been patched up. Would love to have benthos lab up to date

**Comment by Jeffail** [comment]
Still getting `LinkError: data segment does not fit in memory` with Go 1.13.7.

**Comment by DpoBoceka** [comment]
Should we report the unexpected behaviour?

**Comment by Jeffail** [comment]
If we can dig into it more, I'm a little stretched right now so I'd rather not take this on right now.
