### ISSUE TITLE
TinyGO WAMS is getting closer but not quite there.

### ISSUE THREAD

**Issue by joe-getcouragenow** [benthosdev/benthos-lab#20]
https://github.com/tinygo-org/tinygo/blob/master/src/examples/wasm/README.md

It might work because the code is pretty simple.

**Comment by DpoBoceka** [comment]
hey @joe-getcouragenow, there are some difficulties regarding **sync** and **reflect** packages, which are used in main Benthos codebase, which is a dependency of benthos-lab.

**Comment by joe-getcouragenow** [comment]
ah makes sense. thanks for the tip.
I think i should close this.
Come back to it when tinygo has reflect working.
